/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SokRouteImport } from './routes/sok'
import { Route as LaggUppRouteImport } from './routes/lagg-upp'
import { Route as IndexRouteImport } from './routes/index'

const SokRoute = SokRouteImport.update({
  id: '/sok',
  path: '/sok',
  getParentRoute: () => rootRouteImport,
} as any)
const LaggUppRoute = LaggUppRouteImport.update({
  id: '/lagg-upp',
  path: '/lagg-upp',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lagg-upp': typeof LaggUppRoute
  '/sok': typeof SokRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lagg-upp': typeof LaggUppRoute
  '/sok': typeof SokRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lagg-upp': typeof LaggUppRoute
  '/sok': typeof SokRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lagg-upp' | '/sok'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lagg-upp' | '/sok'
  id: '__root__' | '/' | '/lagg-upp' | '/sok'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LaggUppRoute: typeof LaggUppRoute
  SokRoute: typeof SokRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sok': {
      id: '/sok'
      path: '/sok'
      fullPath: '/sok'
      preLoaderRoute: typeof SokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lagg-upp': {
      id: '/lagg-upp'
      path: '/lagg-upp'
      fullPath: '/lagg-upp'
      preLoaderRoute: typeof LaggUppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LaggUppRoute: LaggUppRoute,
  SokRoute: SokRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
